// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package server

import (
	"github.com/maczikasz/go-runs/internal/model"
	"sync"
)

// Ensure, that RunbookStepDetailsFinderMock does implement RunbookStepDetailsFinder.
// If this is not the case, regenerate this file with moq.
var _ RunbookStepDetailsFinder = &RunbookStepDetailsFinderMock{}

// RunbookStepDetailsFinderMock is a mock implementation of RunbookStepDetailsFinder.
//
// 	func TestSomethingThatUsesRunbookStepDetailsFinder(t *testing.T) {
//
// 		// make and configure a mocked RunbookStepDetailsFinder
// 		mockedRunbookStepDetailsFinder := &RunbookStepDetailsFinderMock{
// 			FindRunbookStepDetailsByIdFunc: func(id string) (model.RunbookStepDetails, error) {
// 				panic("mock out the FindRunbookStepDetailsById method")
// 			},
// 		}
//
// 		// use mockedRunbookStepDetailsFinder in code that requires RunbookStepDetailsFinder
// 		// and then make assertions.
//
// 	}
type RunbookStepDetailsFinderMock struct {
	// FindRunbookStepDetailsByIdFunc mocks the FindRunbookStepDetailsById method.
	FindRunbookStepDetailsByIdFunc func(id string) (model.RunbookStepDetails, error)

	// calls tracks calls to the methods.
	calls struct {
		// FindRunbookStepDetailsById holds details about calls to the FindRunbookStepDetailsById method.
		FindRunbookStepDetailsById []struct {
			// ID is the id argument value.
			ID string
		}
	}
	lockFindRunbookStepDetailsById sync.RWMutex
}

// FindRunbookStepDetailsById calls FindRunbookStepDetailsByIdFunc.
func (mock *RunbookStepDetailsFinderMock) FindRunbookStepDetailsById(id string) (model.RunbookStepDetails, error) {
	if mock.FindRunbookStepDetailsByIdFunc == nil {
		panic("RunbookStepDetailsFinderMock.FindRunbookStepDetailsByIdFunc: method is nil but RunbookStepDetailsFinder.FindRunbookStepDetailsById was just called")
	}
	callInfo := struct {
		ID string
	}{
		ID: id,
	}
	mock.lockFindRunbookStepDetailsById.Lock()
	mock.calls.FindRunbookStepDetailsById = append(mock.calls.FindRunbookStepDetailsById, callInfo)
	mock.lockFindRunbookStepDetailsById.Unlock()
	return mock.FindRunbookStepDetailsByIdFunc(id)
}

// FindRunbookStepDetailsByIdCalls gets all the calls that were made to FindRunbookStepDetailsById.
// Check the length with:
//     len(mockedRunbookStepDetailsFinder.FindRunbookStepDetailsByIdCalls())
func (mock *RunbookStepDetailsFinderMock) FindRunbookStepDetailsByIdCalls() []struct {
	ID string
} {
	var calls []struct {
		ID string
	}
	mock.lockFindRunbookStepDetailsById.RLock()
	calls = mock.calls.FindRunbookStepDetailsById
	mock.lockFindRunbookStepDetailsById.RUnlock()
	return calls
}
