POST http://localhost:8080/errors
Content-Type: application/json

{
  "name": "Sentry error",
  "message": "Some message",
  "tags": [
    "error",
    "production"
  ]
}

> {% client.global.set("sessionId", response.body.toString()) %}

###

GET http://localhost:8080/sessions/{{sessionId}}

> {%
     client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
     client.global.set("runbookId", response.body.runbook.id)
%}

###

GET http://localhost:8080/runbooks/{{runbookId}}


> {%
     client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
client.global.set("stepId1", response.body.steps[0].id)
client.global.set("stepId2", response.body.steps[1].id)
client.global.set("stepId3", response.body.steps[2].id)
 %}


###

GET http://localhost:8080/details/{{stepId1}}

> {%
      client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    %}

###

GET http://localhost:8080/details/{{stepId2}}


> {%
      client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    %}

###

GET http://localhost:8080/details/{{stepId3}}


> {%
      client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    %}