// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package handlers

import (
	"github.com/maczikasz/go-runs/internal/model"
	"sync"
)

// RunbookDetailsWriterMock is a mock implementation of RunbookDetailsWriter.
//
// 	func TestSomethingThatUsesRunbookDetailsWriter(t *testing.T) {
//
// 		// make and configure a mocked RunbookDetailsWriter
// 		mockedRunbookDetailsWriter := &RunbookDetailsWriterMock{
// 			CreateRunbookFromDetailsFunc: func(steps []string, name string) (string, error) {
// 				panic("mock out the CreateRunbookFromDetails method")
// 			},
// 		}
//
// 		// use mockedRunbookDetailsWriter in code that requires RunbookDetailsWriter
// 		// and then make assertions.
//
// 	}
type RunbookDetailsWriterMock struct {
	// CreateRunbookFromDetailsFunc mocks the CreateRunbookFromDetails method.
	CreateRunbookFromDetailsFunc func(steps []string, name string) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateRunbookFromDetails holds details about calls to the CreateRunbookFromDetails method.
		CreateRunbookFromDetails []struct {
			// Steps is the steps argument value.
			Steps []string
			// Name is the name argument value.
			Name string
		}
	}
	lockCreateRunbookFromDetails sync.RWMutex
}

// CreateRunbookFromDetails calls CreateRunbookFromDetailsFunc.
func (mock *RunbookDetailsWriterMock) CreateRunbookFromDetails(steps []string, name string) (string, error) {
	if mock.CreateRunbookFromDetailsFunc == nil {
		panic("RunbookDetailsWriterMock.CreateRunbookFromDetailsFunc: method is nil but RunbookDetailsWriter.CreateRunbookFromDetails was just called")
	}
	callInfo := struct {
		Steps []string
		Name  string
	}{
		Steps: steps,
		Name:  name,
	}
	mock.lockCreateRunbookFromDetails.Lock()
	mock.calls.CreateRunbookFromDetails = append(mock.calls.CreateRunbookFromDetails, callInfo)
	mock.lockCreateRunbookFromDetails.Unlock()
	return mock.CreateRunbookFromDetailsFunc(steps, name)
}

// CreateRunbookFromDetailsCalls gets all the calls that were made to CreateRunbookFromDetails.
// Check the length with:
//     len(mockedRunbookDetailsWriter.CreateRunbookFromDetailsCalls())
func (mock *RunbookDetailsWriterMock) CreateRunbookFromDetailsCalls() []struct {
	Steps []string
	Name  string
} {
	var calls []struct {
		Steps []string
		Name  string
	}
	mock.lockCreateRunbookFromDetails.RLock()
	calls = mock.calls.CreateRunbookFromDetails
	mock.lockCreateRunbookFromDetails.RUnlock()
	return calls
}

// RunbookDetailsFinderMock is a mock implementation of RunbookDetailsFinder.
//
// 	func TestSomethingThatUsesRunbookDetailsFinder(t *testing.T) {
//
// 		// make and configure a mocked RunbookDetailsFinder
// 		mockedRunbookDetailsFinder := &RunbookDetailsFinderMock{
// 			FindRunbookDetailsByIdFunc: func(id string) (model.RunbookDetails, error) {
// 				panic("mock out the FindRunbookDetailsById method")
// 			},
// 			ListAllRunbooksFunc: func() ([]model.RunbookSummary, error) {
// 				panic("mock out the ListAllRunbooks method")
// 			},
// 		}
//
// 		// use mockedRunbookDetailsFinder in code that requires RunbookDetailsFinder
// 		// and then make assertions.
//
// 	}
type RunbookDetailsFinderMock struct {
	// FindRunbookDetailsByIdFunc mocks the FindRunbookDetailsById method.
	FindRunbookDetailsByIdFunc func(id string) (model.RunbookDetails, error)

	// ListAllRunbooksFunc mocks the ListAllRunbooks method.
	ListAllRunbooksFunc func() ([]model.RunbookSummary, error)

	// calls tracks calls to the methods.
	calls struct {
		// FindRunbookDetailsById holds details about calls to the FindRunbookDetailsById method.
		FindRunbookDetailsById []struct {
			// ID is the id argument value.
			ID string
		}
		// ListAllRunbooks holds details about calls to the ListAllRunbooks method.
		ListAllRunbooks []struct {
		}
	}
	lockFindRunbookDetailsById sync.RWMutex
	lockListAllRunbooks        sync.RWMutex
}

// FindRunbookDetailsById calls FindRunbookDetailsByIdFunc.
func (mock *RunbookDetailsFinderMock) FindRunbookDetailsById(id string) (model.RunbookDetails, error) {
	if mock.FindRunbookDetailsByIdFunc == nil {
		panic("RunbookDetailsFinderMock.FindRunbookDetailsByIdFunc: method is nil but RunbookDetailsFinder.FindRunbookDetailsById was just called")
	}
	callInfo := struct {
		ID string
	}{
		ID: id,
	}
	mock.lockFindRunbookDetailsById.Lock()
	mock.calls.FindRunbookDetailsById = append(mock.calls.FindRunbookDetailsById, callInfo)
	mock.lockFindRunbookDetailsById.Unlock()
	return mock.FindRunbookDetailsByIdFunc(id)
}

// FindRunbookDetailsByIdCalls gets all the calls that were made to FindRunbookDetailsById.
// Check the length with:
//     len(mockedRunbookDetailsFinder.FindRunbookDetailsByIdCalls())
func (mock *RunbookDetailsFinderMock) FindRunbookDetailsByIdCalls() []struct {
	ID string
} {
	var calls []struct {
		ID string
	}
	mock.lockFindRunbookDetailsById.RLock()
	calls = mock.calls.FindRunbookDetailsById
	mock.lockFindRunbookDetailsById.RUnlock()
	return calls
}

// ListAllRunbooks calls ListAllRunbooksFunc.
func (mock *RunbookDetailsFinderMock) ListAllRunbooks() ([]model.RunbookSummary, error) {
	if mock.ListAllRunbooksFunc == nil {
		panic("RunbookDetailsFinderMock.ListAllRunbooksFunc: method is nil but RunbookDetailsFinder.ListAllRunbooks was just called")
	}
	callInfo := struct {
	}{}
	mock.lockListAllRunbooks.Lock()
	mock.calls.ListAllRunbooks = append(mock.calls.ListAllRunbooks, callInfo)
	mock.lockListAllRunbooks.Unlock()
	return mock.ListAllRunbooksFunc()
}

// ListAllRunbooksCalls gets all the calls that were made to ListAllRunbooks.
// Check the length with:
//     len(mockedRunbookDetailsFinder.ListAllRunbooksCalls())
func (mock *RunbookDetailsFinderMock) ListAllRunbooksCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockListAllRunbooks.RLock()
	calls = mock.calls.ListAllRunbooks
	mock.lockListAllRunbooks.RUnlock()
	return calls
}
